@startuml Universidade sem package
left to right direction

actor Reitor as r
actor Aluno as a
actor Coordenador as co
actor Professor as p
actor Faxineirio as fx
actor Vigilante as v
actor Financeiro as f

usecase "Pagar Salário" as uc8
usecase "Receber salário" as uc11
usecase "Orientar Matrícula" as uc3
usecase "Administrar Curso" as uc4
usecase "Cuidar do Patrimônio" as uc9
usecase "Limpeza" as uc10
usecase "Administrar Universidade" as uc1
usecase "Representar Universidade" as uc2
usecase "Ministrar Aula" as uc5
usecase "Assistir Aula" as uc6

r --|> co
co --|> p
r --> uc1
r --> uc2
co --> uc3
co --> uc4
p --> uc5
a --> uc6
r --|> p
uc8 --> fx
uc8 --> p
uc8 --> co
uc8 --> v
p --|> a
uc5 --> a
uc6 --> p
v --> uc9
fx --> uc10
fx --> uc11
p --> uc11
co --> uc11
v --> uc11
r --|> fx
r --|> v
f --> uc8
r --|> f
uc11 --> f
@enduml